(package-initialize)
(require 'cl)
(require 'yasnippet)
;; 加载其他配置
(add-to-list 'load-path "~/.emacs.d/lisp/")
(add-to-list 'load-path "~/.emacs.d/lisp/evil")
(add-to-list 'load-path "~/.emacs.d/lisp/evil-nerd-commenter")
(require 'undo-tree)
(require 'evil)
(require 'evil-leader)
(require 'evil-surround)
(require 'evil-nerd-commenter)
(require 'which-key)
(require 'gnu-elpa-keyring-update)
(require 'init-package)
(require 'init-ui)
(require 'init-better-set)
(require 'init-custom)
(require 'init-key)
